# Generated by Django 3.1.1 on 2024-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240430_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
