# Generated by Django 3.1.1 on 2024-05-05 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_consultation',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hospital'),
        ),
        migrations.AddField(
            model_name='doctoradd',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor_consultation',
            name='Doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.doctoradd'),
        ),
    ]
