# Generated by Django 3.1.1 on 2024-05-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240505_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_consultation',
            name='Patiant_disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
